/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject3.ControllerAndView.Home;

import com.mycompany.mavenproject3.ControllerAndView.Interface.ViewInterface;
import java.awt.event.ActionListener;

/**
 *
 * @author azoom
 */
public class HomeView 
        extends javax.swing.JFrame 
        implements ViewInterface
{
    
    public HomeView() {
        initComponents();
    }

    public void add_Listener_VatPham_Button(ActionListener a){
        this.vatPham.addActionListener(a);
    }
    
    public void add_Listener_MotLuotBan_Button(ActionListener a){
        this.motLuotBan.addActionListener(a);
    }
    
    public void add_Listener_HoaDonBan_Button(ActionListener a){
        this.motLuotNhap.addActionListener(a);
    }
    
    public void add_Listener_UserButton_Button(ActionListener a){
        this.userButton.addActionListener(a);
    }
    
    public void add_Listener_MotLuotNhap_Button(ActionListener a){
        this.motLuotNhap.addActionListener(a);
    }
    
    @Override
    public void deleteContent() {
        // doesnt do
    }

    @Override
    public void hideView() {
        this.setVisible(false);
    }

    @Override
    public void showView() {
        this.setVisible(true);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vatPham = new javax.swing.JButton();
        motLuotBan = new javax.swing.JButton();
        motLuotNhap = new javax.swing.JButton();
        userButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("This is home view");

        vatPham.setText("Vật phẩm");
        vatPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vatPhamActionPerformed(evt);
            }
        });

        motLuotBan.setText("Một lượt bán");

        motLuotNhap.setText("Một lượt nhập");
        motLuotNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motLuotNhapActionPerformed(evt);
            }
        });

        userButton.setText("User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(vatPham)
                    .addComponent(motLuotBan)
                    .addComponent(motLuotNhap)
                    .addComponent(userButton))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vatPham)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motLuotBan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motLuotNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userButton)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vatPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vatPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vatPhamActionPerformed

    private void motLuotNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motLuotNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motLuotNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton motLuotBan;
    private javax.swing.JButton motLuotNhap;
    private javax.swing.JButton userButton;
    private javax.swing.JButton vatPham;
    // End of variables declaration//GEN-END:variables
}
